spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dnd
    username: root
    password: DNKIP}yVG+Er2q%X
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: dev

